POST  http://127.0.0.1:3333/auth/login 
Content-Type: application/json

{
  "email": "Eden_Nienow@hotmail.com",
  "password": "admin"
}

###

GET http://127.0.0.1:3333/App/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOiIzOWZhNjI2MC1iN2RlLTRiYmEtOGE2ZS0wNGFkOWU0N2RkYzMiLCJpYXQiOjE3MzUzMDg5NzIsImV4cCI6MTczNTMxMjU3Mn0.0fo6PN__cbunfprwrFzBG3uq1mqas17_kMSvrtKUdfE


###

GET http://127.0.0.1:3333/Dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOiIzOWZhNjI2MC1iN2RlLTRiYmEtOGE2ZS0wNGFkOWU0N2RkYzMiLCJpYXQiOjE3MzUzMDg5NzIsImV4cCI6MTczNTMxMjU3Mn0.0fo6PN__cbunfprwrFzBG3uq1mqas17_kMSvrtKUdfE

###

POST http://127.0.0.1:3333/Dashboard/black-list/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOiIzOWZhNjI2MC1iN2RlLTRiYmEtOGE2ZS0wNGFkOWU0N2RkYzMiLCJpYXQiOjE3MzUzMDg5NzIsImV4cCI6MTczNTMxMjU3Mn0.0fo6PN__cbunfprwrFzBG3uq1mqas17_kMSvrtKUdfE
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOiIzOWZhNjI2MC1iN2RlLTRiYmEtOGE2ZS0wNGFkOWU0N2RkYzMiLCJpYXQiOjE3MzUzMDg5NzIsImV4cCI6MTczNTMxMjU3Mn0.0fo6PN__cbunfprwrFzBG3uq1mqas17_kMSvrtKUdfE"
}